{% set name = "lsst-ts-xml" %}
{% set version = "20.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst-ts/ts_xml/archive/v{{ version }}.tar.gz
  sha256: 04a8c8053c1c26180b689c61ab470de8117f6ac243158f17b17aa1a288dfc5fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools_scm
  run:
    - python >=3.10
    - astropy
    - __unix

test:
  source_files:
    - tests
  imports:
    - lsst.ts.xml
  requires:
    - pytest
    - lxml
  commands:
    - pytest

about:
  home: https://github.com/lsst-ts/ts_xml
  summary: 'Contains XML files used to generate SAL data.'
  description: |
    ts-xml is used by ts_sal to generate the commands, events and telemetry
    for various components used by the Vera C. Rubin Observatory for the
    Simonyi Survey Telescope.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://ts-xml.lsst.io/
  dev_url: https://github.com/lsst-ts/ts_xml

extra:
  recipe-maintainers:
    - couger01
    - tribeiro
    - rbovill
