{% set name = "lsst-ts-xml" %}
{% set version = "24.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsst-ts/ts_xml/archive/v{{ version }}.tar.gz
  sha256: 14b233b75db2f670ab450f1f35bed0d6d947dd03582d1efd97a502f3f5d77c16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - astropy-base
    - __unix

test:
  source_files:
    - tests
  imports:
    - lsst.ts.xml
  requires:
    - python {{ python_min }}
    - pytest
    - lxml
  commands:
    - pytest

about:
  home: https://github.com/lsst-ts/ts_xml
  summary: 'Contains XML files used to generate SAL data.'
  description: |
    ts-xml is used by ts_sal to generate the commands, events and telemetry
    for various components used by the Vera C. Rubin Observatory for the
    Simonyi Survey Telescope.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://ts-xml.lsst.io/
  dev_url: https://github.com/lsst-ts/ts_xml

extra:
  recipe-maintainers:
    - couger01
    - tribeiro
    - rbovill
